# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f61de07211f6005d57383afc1b36c0c011998d8dc2937752420aab52fd993bf0b881687ea895f49fcea7eeaeded3e18e565c8ed8416e6093d04b616a4bf5b91d

test:
  secret_key_base: 421b9546f3482864defd028b6574b84ec59e18ef560c140f8979c57715b7ffee530119b9b3ecb4604b9588b26b0079857f00b33aba55920e0ef51a89b6cce252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
